### ISSUE TITLE
Improve CSS

### ISSUE THREAD

**Issue by jabrena** [mindstormschallenges/challenge1#2]
**Section "Start"**
Improve CSS for H2

**Section "Rules"**
Improve CSS for Links on UL
Links need a dark color. Besides it is necessary underline style and hover effect

List about elements:

``` bash
folder with your github user
a cad/ldraw with the model
a image with the model
```

This list need a bullet

**Comment by Suriv** [comment]
Upload

**Comment by jabrena** [comment]
Fixed.
